### ISSUE TITLE
Agentをステートフルシングルトンにするパターン

### ISSUE THREAD

**Issue by yuka1984** [TsuyoshiUshio/FunctionsLoadTesting#1]
https://github.com/yuka1984/FunctionsLoadTesting/tree/SubOrchestrationPattern

昨日はありがとうございました。モブプログラミングが中途半端で終わっていて気になったのでDurableFunctionsを使用した可能なアーキテクチャで1000agent分を終わらせられるパターンを書いてみました。
White文でループしている部分をEternal orchestrationsに置き換えています。

昨日はContinuAsNew関数の存在に気がついていなかったので提案できませんでしたが、DurableFunctionsでも一つのオーケストレータを永続的に動かすアーキテクチャが実装されていました。

https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-eternal-orchestrations

**Comment by TsuyoshiUshio** [comment]
ありがとうございます。私の方でも教えていただいた方法を使って実際やってみましたが、正しく動作しますが、レイテンシーがよくなかったです。ドキュメントを見ると ContinueAsNew をすると自分自身に、キューを送る感じなので、きっと１０００ Agent ぐらいになったら、キューを待つのだろうなと想像して、10 Agent で、 各Agent が100スレッド実行　終わったら ContinueAsNew のパターンもやってみましたが、こちらのほうがレスポンスはましでしたが、レイテンシーにばらつきがありました（早ければ１秒いかないですが、遅いと何分というオーダーに。無限ループ系にはこのやり方が Durable 的には正しい気がしていて、ほかには、前のやり方で、Agent 10 個 x 100 スレッドを回しっぱなしで、そのループのなかで、Table ストレージを監視していて、instance id が同じデータが書かれたら Cancellation Token を吐いてグレースフルに終わるパターンも考えましたが、ちょいややこしいし、きっとDurable Functions が想定していない動きだと思うので、ブログ書いてクローズしてみます。Durable は継続的に他のユースケースでも使ってみます。とても勉強になりました。ありがとうございました！
